### ISSUE TITLE
yaml files 

### ISSUE THREAD

**Issue by xHirscHx** [PxPert/esphome#1]
Iv tried every combo of yaml files to get this to work and it seems like something is missing.
Every time i get some kind off error.  Can you make a readme, step by step to help out. Allso im just looking for RGB light ( wled style ) control with voice  no touch needed if possible.

**Comment by xHirscHx** [comment]
INFO ESPHome 2024.3.1
INFO Reading configuration /config/esphome/tx-test-2.yaml...
WARNING Found '${friendly_name} Vibration' (see button->3->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${friendly_name} (Safe Mode)' (see button->4->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${friendly_name} Restart' (see button->5->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${mic_lrclk_pin}' (see i2s_audio->0->i2s_lrclk_pin) which looks like a substitution, but 'mic_lrclk_pin' was not declared
WARNING Found '${mic_bclk_pin}' (see i2s_audio->0->i2s_bclk_pin) which looks like a substitution, but 'mic_bclk_pin' was not declared
WARNING Found '${mic_sdata_pin}' (see microphone->0->i2s_din_pin) which looks like a substitution, but 'mic_sdata_pin' was not declared
WARNING Found '${friendly_name} Vibration' (see button->3->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${friendly_name} (Safe Mode)' (see button->4->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${friendly_name} Restart' (see button->5->name) which looks like a substitution, but 'friendly_name' was not declared
WARNING Found '${mic_lrclk_pin}' (see i2s_audio->0->i2s_lrclk_pin) which looks like a substitution, but 'mic_lrclk_pin' was not declared
WARNING Found '${mic_bclk_pin}' (see i2s_audio->0->i2s_bclk_pin) which looks like a substitution, but 'mic_bclk_pin' was not declared
WARNING Found '${mic_sdata_pin}' (see microphone->0->i2s_din_pin) which looks like a substitution, but 'mic_sdata_pin' was not declared
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

globals: [source /config/esphome/tx_ultimate_voice_assistant.yaml:69]
  
  'type' is a required option for [0].
  - 
    Source for extension of ID 'ww_switch' was not found.
    id: !extend ww_switch
    initial_value: use_wake_word
    restore_value: False
  - 
    Source for extension of ID 'start_assistant_button' was not found.
    id: !extend start_assistant_button
    type: template_::TemplateButton*
    initial_value: start_assistant
    restore_value: False
  - id: va_capturing
    type: bool
    initial_value: false
    restore_value: False
  - id: suspend_refresh
    type: bool
    initial_value: false
    restore_value: False
  - id: leds_list
    type: light::AddressableLightState*[1]
    initial_value: {leds}
    restore_value: False
  - id: relay_states
    type: bool[1]
    initial_value: {false}
    restore_value: True
  - id: relay_count
    type: int
    initial_value: 1
    restore_value: False
  - id: va_state
    type: bool
    initial_value: false
    restore_value: True
  - id: led_with_va_on
    type: light::AddressableLightState*
    initial_value: NULL
    restore_value: False
  - id: ww_switch
    type: template_::TemplateSwitch*
    initial_value: NULL
    restore_value: False
  - id: start_assistant_button
    type: template_::TemplateButton*
    initial_value: NULL
    restore_value: False
  - id: button_color
    type: int [4]
    restore_value: False
    initial_value: {33,100,56,100}
  - id: touch_color
    type: int [4]
    restore_value: False
    initial_value: {0,100,100,100}
  - id: va_color
    type: int [4]
    restore_value: False
    initial_value: {0,0,100,75}
  - id: swipe_left_color
    type: int [4]
    restore_value: False
    initial_value: {19,100,100,100}
  - id: swipe_right_color
    type: int [4]
    restore_value: False
    initial_value: {100,0,70,100}
  - id: nightlight_color
    type: int [4]
    restore_value: False
    initial_value: {80,70,0,20}
i2s_audio: [source /config/esphome/tx_ultimate_voice_assistant.yaml:125]
  - id: audio_mic_i2s
    
    Cannot resolve pin name '${mic_lrclk_pin}' for board esp32dev.
    i2s_lrclk_pin: ${mic_lrclk_pin}
    
    Cannot resolve pin name '${mic_bclk_pin}' for board esp32dev.
    i2s_bclk_pin: ${mic_bclk_pin}
  - id: audio_i2s
    i2s_lrclk_pin: 4
    i2s_bclk_pin: 2
microphone.i2s_audio: [source /config/esphome/tx_ultimate_voice_assistant.yaml:141]
  platform: i2s_audio
  i2s_audio_id: audio_mic_i2s
  
  Cannot resolve pin name '${mic_sdata_pin}' for board esp32dev.
  i2s_din_pin: ${mic_sdata_pin}
  adc_type: external
  id: mic_i2s
  pdm: False
esp_adf: [source /config/esphome/tx_ultimate_voice_assistant.yaml:148]
  
  Component not found: esp_adf.
voice_assistant: [source /config/esphome/tx_ultimate_voice_assistant.yaml:152]
  id: va
  microphone: mic_i2s
  speaker: audio_out
  
  This option requires component esp_adf.
  vad_threshold: 5
  use_wake_word: False
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0
  on_wake_word_detected: 
    - globals.set: 
        id: va_capturing
        value: true
    - light.turn_on: 
        id: leds
        red: 0
        green: 0
        blue: 1
        brightness: 1
        effect: Scan
  on_stt_vad_start: 
    - globals.set: 
        id: va_capturing
        value: true
    - light.turn_on: 
        id: leds
        red: 0
        green: 1
        blue: 0
        brightness: 1
        effect: Scan
  on_tts_start: 
    - globals.set: 
        id: va_capturing
        value: false
    - if: 
        condition: 
          lambda: return x == "Mi dispiace, non ho capito";
        then: 
          - light.turn_on: 
              id: leds
              red: 1
              green: 0
              blue: 0
              brightness: 1
              effect: None
        else: 
          - light.turn_on: 
              id: leds
              effect: None
              red: 0
              green: 1
              blue: 0
              brightness: 1
  on_tts_stream_end: 
    - delay: 1s
    - script.execute: refresh_led_full_off_default
  on_start: 
    - if: 
        condition: 
          - lambda: return id(va).is_continuous();
        then: 
          - globals.set: 
              id: va_state
              value: true
          - script.execute: refresh_led_default
  on_end: 
    - if: 
        condition: 
          - lambda: return id(va_capturing);
        then: 
          - globals.set: 
              id: va_capturing
              value: false
          - globals.set: 
              id: va_state
              value: false
          - delay: 2s
          - script.execute: refresh_led_full_off_default
  on_error: 
    - script.execute: refresh_led_default
  on_client_connected: 
    - if: 
        condition: 
          switch.is_on: use_wake_word
        then: 
          - voice_assistant.start_continuous: {}
  on_client_disconnected: 
    - if: 
        condition: 
          switch.is_on: use_wake_word
        then: 
          - voice_assistant.stop: {}

**Comment by xHirscHx** [comment]
witch yaml file do i start with. It seems that is not including or pulling the correct files from the include folder. 
I got it to work partly ( not thro errors when compiling )putting everything in one folder and deleting duplicates.

**Comment by PxPert** [comment]
Hi, sorry for the delay.
Please clone the repo or import the exact project structure for the configuration to work correctly.
Start from the tx_ultimate_00_base.yaml to write a configuration. I've added some documentation to it.
All the logic (Led functionality, virtual buttons, voice assistant) are automatically created based on the packages you include in the base file, so you don't have to edit any of the yamls in the include folder.
Take a look to the other tx_ultimate_XX_* yaml file to better understand the logic of my configuration!

Here: https://www.youtube.com/watch?v=AVS_tiUuSgQ you can find a video of one of my devices working with this setup!
